// Code generated by mockery v2.35.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Notificator is an autogenerated mock type for the Notificator type
type Notificator struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: message
func (_m *Notificator) SendMessage(message string) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificator creates a new instance of Notificator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Notificator {
	mock := &Notificator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
